### ISSUE TITLE
How to specify connection parameters?

### ISSUE THREAD

**Issue by Sogl** [rayed/smpp_php#1]
Hi!

How can I specify this:
- source_addr_ton = 5
- source_addr_npi = 0
- dest_addr_ton = 1
- dest_addr_npi = 1

with your script?

**Comment by rayed** [comment]
You can change it in line 102 in function "submit_sm".
Sorry for not providing a cleaner way but I don't use this module anymore so I can't test my changes.

**Comment by Sogl** [comment]
Just tried your script and it works fine. Thank you! :+1:
