### ISSUE TITLE
Multipart and line-break

### ISSUE THREAD

**Issue by Sogl** [rayed/smpp_php#2]
Hi!

I use this tool for test:
http://www.inetlab.com/Products/Inetlab.SMPP.aspx

If I send SMS with 137 Russian chars then I see one message in my phone.
Same message with your tool divided into 3 parts (3 SMS in phone). Max part symbols is 65.
How to send it in one message?

Also how to add line-break? `\n` don't work.

**Comment by rayed** [comment]
I really don't recal that much on how SMPP works, but as far as I remember if you need to send non ascii characters you have to use UTF-16 Big Endian.

In general if your message is longer than 160, you should use "send_long" to send it as multiple 160 long messges.

e.g. If your message is 100 char long in non ASCII, it would be 200 bytes long in UTF-16, and send_long will send 2 sperate messages, the first is 160 bytes, and the second is 40 bytes.

About the new line, try "\r\n" it might work!

**Comment by Sogl** [comment]
So...why InetlabSMPP tool send 1 SMS with the same 137 non-ASCII chars, but php solution break it into 3 SMS by 65 symbols maximum? Maybe I miss something?

**Comment by rayed** [comment]
I have no idea, I wrote this software more than 8 years ago, and I haven't used SMPP since!
