### ISSUE TITLE
How to get Message ID?

### ISSUE THREAD

**Issue by ruturajpatki** [rayed/smpp_php#3]
First, your class works really well; thanks so much for your hard work. 

I need following things which I'm not able to implement with your Class...

1. Message ID: SMPP specifications says this is in SM_RESP body. I see you read PDU and retrieve ID, Status and Sequence which are in Header. How to get the Message ID? 

2. SMPP Delivery Status: SMPP specifications have some codes defined for SMPP Message Delivery Status. Is it possible for me to check the Status Code of Message Delivery in Transeceiver mode? If not, is there any way to query status of the message by any of the fields you're already retrieving in your class?

Waiting for your reply...

Thanks!

**Comment by rayed** [comment]
Sorry Ruturaaj, but I haven’t worked with SMPP in a decade

**Comment by ruturajpatki** [comment]
Thanks so much for your reply; but can you provide me some hint with the code? Or perhaps a good link that will help me to work with SMPP in transeceiver mode? I searched and found very few PHP classes; but none of those are close to the performance efficiency of your class.
